# Copyright (c) 2012 Partners In Health.  All rights reserved.
# The use and distribution terms for this software are covered by the
# Eclipse Public License 1.0 (http://opensource.org/licenses/eclipse-1.0.php)
# which can be found in the file epl-v10.html at the root of this distribution.
# By using this software in any fashion, you are agreeing to be bound by
# the terms of this license.
# You must not remove this notice, or any other, from this software.

---
grails:
    profile: web
    codegen:
        defaultPackage: org
    gorm:
        reactor:
            # Whether to translate GORM events into Reactor events
            # Disabled by default for performance reasons
            events: false
        failOnError: false

info:
    app:
        name: '@info.app.name@'
        version: '@info.app.version@'
        grailsVersion: '@info.app.grailsVersion@'
spring:
    main:
        banner-mode: "off"
    groovy:
        template:
            check-template-location: false

# Spring Actuator Endpoints are Disabled by Default
endpoints:
    enabled: false
    jmx:
        enabled: true

---
grails:
    #serverURL: "http://localhost:8080/${appName}"
    doc:
        title: "OpenBoxes"
        subtitle: ""
        authors: "Justin Miranda"
        license: "Eclipse Public License - Version 1.0"
        copyright: ""
        footer: ""
    mail:
        enabled: false
        from: "info@openboxes.com"
        prefix: "[OpenBoxes]"
        host: "localhost"
        port: "25"
    
        # Authentication disabled by default
        username: null
        password: null
    
        # Disable debug mode by default
        debug: false
    mime:
        disable:
            accept:
                header:
                    userAgents:
                        - Gecko
                        - WebKit
                        - Presto
                        - Trident
        types:
            all: '*/*'
            atom: application/atom+xml
            css: text/css
            csv: text/csv
            form: application/x-www-form-urlencoded
            html:
              - text/html
              - application/xhtml+xml
            js: text/javascript
            json:
              - application/json
              - text/json
            multipartForm: multipart/form-data
            pdf: application/pdf
            rss: application/rss+xml
            text: text/plain
            hal:
              - application/hal+json
              - application/hal+xml
            xml:
              - text/xml
              - application/xml
        file:
            extensions: true
        use:
            accept:
                header: false
    urlmapping:
        cache:
            maxsize: 1000
    controllers:
        defaultScope: singleton
    converters:
        encoding: UTF-8
    views:
        default:
            codec: none
        enable:
            jsessionid: true
        gsp:
            encoding: UTF-8
            htmlcodec: xml
            codecs:
                expression: html
                scriptlets: html
                taglib: none
                staticparts: none
            sitemesh:
                preprocess: true
        javascript:
            library: jquery
endpoints:
    jmx:
        unique-names: true

---
hibernate:
    cache:
        queries: false
        use_second_level_cache: false
        use_query_cache: false

dataSource:
    pooled: true
    jmxExport: true
    driverClassName: com.mysql.jdbc.Driver
    username: 'root'
    password: 'root'
    dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    logSql: false
    formatSql: false
    properties:
        jmxEnabled: true
        initialSize: 10
        maxActive: 100
        minIdle: 5
        maxIdle: 25
        maxWait: 10000
        maxAge: 14400
        timeBetweenEvictionRunsMillis: 5000
        minEvictableIdleTimeMillis: 60000
        validationQuery: SELECT 1
        validationQueryTimeout: 3
        validationInterval: 15000
        testOnBorrow: true
        testWhileIdle: true
        testOnReturn: false
        jdbcInterceptors: ConnectionState
        defaultTransactionIsolation: 2 # TRANSACTION_READ_COMMITTED

environments:
    development:
        dataSource:
            dbCreate: create-drop
            url: jdbc:mysql://localhost:3306/openboxes
    test:
        dataSource:
            dbCreate: update
            url: jdbc:mysql://localhost:3306/openboxesf
    production:
        dataSource:
            dbCreate: none
            url: jdbc:mysql://localhost:3306/openboxes
    diff:
        dataSource:
            url: jdbc:mysql://localhost:3306/openboxes_diff

---
openboxes:
    # Dashboard configuration to allow specific ordering of widgets (overrides enabled/disabled config)
    dashboard:
        column1:
            widgets: ["requisitionItemSummary", "requisitionSummary", "receiptSummary", "shipmentSummary", "indicatorSummary"]
        column2:
            widgets: ["binLocationSummary", "expiringSummary", "productSummary", "genericProductSummary",]
        column3:
            widgets: ["newsSummary", "activitySummary", "valueSummary", "tagSummary", "catalogsSummary"]
        
        # Column 1
        requisitionItemSummary:
            enabled: true
        requisitionSummary:
            enabled: false
        receiptSummary:
            enabled: true
        shipmentSummary:
            enabled: true
        indicatorSummary:
            enabled: false
        
        # Column 2
        binLocationSummary:
            enabled: true
        productSummary:
            enabled: true
        genericProductSummary:
            enabled: false
        expiringSummary:
            enabled: true
        
        # Column 3
        newsSummary:
            enabled: false
        activitySummary:
            enabled: true
        valueSummary:
            enabled: false
        tagSummary:
            enabled: true
        catalogsSummary:
            enabled: true
        
        # Default value for news summary
        newsSummary:
            newsItems: []

    # OpenBoxes identifier config
    identifier:
        numeric: "0123456789"
        alphabetic: "ABCDEFGHJKMNPQRSTUVXYZ"
        alphanumeric: "0123456789ABCDEFGHJKMNPQRSTUVWXYZ"
        transaction:
            format: "AAA-AAA-AAA"
        order:
            format: "NNNLLL"
        product:
            format: "LLNN"
        productSupplier:
            format: "LLNN"
        receipt:
            format: "NNNLLL"
        requisition:
            format: "NNNLLL"
        shipment:
            format: "NNNLLL"
    
    # OpenBoxes default line printer port
    linePrinterTerminal:
        port: "LPT1"
    
    # OpenBoxes default uploads directory location
    uploads:
        location: "uploads"
        

    # Fullstory integration
    fullstory:
        enabled: false
        debug: false
        host: "fullstory.com"
        org: ""
        namespace: "FS"

    # Hotjar integration
    hotjar:
        enabled: false
        hjid: 0
        hjsv: 6

    # Forecasting feature
    forecasting:
        enabled: false

    # Bill of Materials feature
    bom:
        enabled: false

    # UserVoice widget
    uservoice:
        widget:
            enabled: true
            position: "right"

    # UserVoice widget
    zopim:
        widget:
            enabled: false
            url: "//v2.zopim.com/?2T7RMi7ERqr3s8N20KQ3wOBRudcwosBA"

    # JIRA Issue Collector
    jira:
        issue:
            collector:
                enabled: false
                url: "https://openboxes.atlassian.net/s/d41d8cd98f00b204e9800998ecf8427e/en_USgc5zl3-1988229788/6318/12/1.4.10/_/download/batch/com.atlassian.jira.collector.plugin.jira-issue-collector-plugin:issuecollector/com.atlassian.jira.collector.plugin.jira-issue-collector-plugin:issuecollector.js?collectorId=fb813fdb"

    # OpenBoxes Feedback
    mail:
        feedback:
            enabled: false
            recipients: ["feedback@openboxes.com"]
        # OpenBoxes Error Emails (bug reports)
        errors:
            enabled: true
            recipients: ["errors@openboxes.com"]

    # Barcode scanner (disabled by default)
    scannerDetection:
        enabled: false
    
    
    # Default delay and min length for typeahead components
    typeahead:
        delay: 300
        minLength: 3
    
    # Send stock alerts
    jobs:
        sendStockAlertsJob:
            enabled: true
            skipOnEmpty: true
            daysUntilExpiry: 60
            cronExpression: "0 0 0 * * ?" # every day at midnight
    
        # Refresh inventory snapshots
        refreshInventorySnapshotJob:
            enabled: true
        
        # Refresh transaction fact table
        refreshTransactionFactJob:
            enabled: true
            cronExpression: "0 0 0 * * ?" # every day at midnight
        
        # Assign identifier job
        assignIdentifierJob:
            enabled: true
            cronExpression: "0 * * * * ?" # every five minutes
        
        # Calculate current quantity on hand
        calculateQuantityJob:
            enabled: true
            cronExpression: "0 */5 * * * ?" # every five minutes
        
        # Calculate historical quantity on hand
        calculateHistoricalQuantityJob:
            enabled: false
            cronExpression: "0 0 0 * * ?" # every day at midnight
            daysToProcess: 540   // 18 months
        
        # Data Cleaning Job
        dataCleaningJob:
            enabled: true
            cronExpression: "0 */5 * * * ?"       # every five minutes
        
        # Data Migration Job (enabled, but needs to be triggered manually)
        dataMigrationJob:
            enabled: true
    
    # LDAP configuration
    ldap:
        enabled: false
        context:
            managerDn: "cn=read-only-admin,dc=example,dc=com"
            managerPassword: "password"
            server:
                host: "ldap.forumsys.com"
                port: 389
    
        # LDAP Search
        search:
            base: "dc=example,dc=com"
            filter: "(uid={0})"
            searchSubtree: true
            attributesToReturn: ['mail', 'givenName']
    
    # Stock Card > Consumption > Reason codes
    # Examples: Stock out, Low stock, Expired, Damaged, Could not locate, Insufficient quantity reconditioned
    stockCard:
        consumption:
            stouckout: &stockout 1
            low_stock: &low_stock 2
            expired: &expired 3
            damaged: &damaged 4
            could_not_locate: &could_not_locate 14
            insufficient_quantity_reconditioned: &insufficient_quantity_reconditioned 19
            reasonCodes: [*stockout, *low_stock, *expired, *damaged, *could_not_locate, *insufficient_quantity_reconditioned]
    
    # Localization configuration - default and supported locales
    locale:
        custom:
            enabled: false
        defaultLocale: 'en'
        supportedLocales: ['ar', 'en', 'fr', 'de', 'it', 'es', 'pt']
        # Currency configuration
        defaultCurrencyCode: "USD"
        defaultCurrencySymbol: '\$'
    
    # Inventory snapshot configuration
    inventorySnapshot:
        batchSize: 1500
    
    # Global megamenu configuration
    megamenu:
        dashboard:
            enabled: true
        analytics:
            enabled: true
        inventory:
            enabled: true
        orders:
            enabled: true
        requisitions:
            enabled: true
        shipping:
            enabled: true
        stockMovement:
            enabled: true
        receiving:
            enabled: true
        reporting:
            enabled: true
        products:
            enabled: true
        configuration:
            enabled: true
        customLinks:
            enabled: false
        inbound:
            enabled: true
        outbound:
            enabled: true
        requisitionTemplate:
            enabled: true

    # Allow users to customize logo image url as well as label
    logo:
        url: "https://openboxes.com/img/logo_30.png"
    report:
        logo:
            url: "https://openboxes.com/img/logo_100.png"

    # Allow system to anonymize user data to prevent it from being accessed by unauthorized users
    anonymize:
        enabled: false

    generateName:
        separator: " - "

    # Disable feature during development
    shipping:
        splitPickItems.enabled: true

    # Add item to shipment search
    shipping:
        search:
        maxResults: 1000

    # Automatically create temporary receiving locations for shipments
    receiving:
        createReceivingLocation:
            enabled: true
        receivingLocation:
            prefix: "R"

    # Indicates which activities are required for a location to allow logins
    chooseLocation:
        requiredActivities: ["MANAGE_INVENTORY"]

mail:
    error:
        enabled: false
        debug: false
        to: 'errors@openboxes.com'
        server: "localhost"
        port: "25"
        from: "info@openboxes.com"
        username: null
        password: null
        prefix: "[OpenBoxes]"

uiperformance:
    enabled: false

# TODO OBGM 1: Add jqueryValidation plugin config if will be needed
# TODO OBGM 2: Add log4j plugin config if will be needed
# TODO OBGM 3: Add springcache plugin config if will be needed
# TODO OBGM 4: Add raven plugin config if will be needed
# TODO OBGM 5: Add Joda-Time plugin config if will be needed
# TODO OBGM 6: Add resources plugin config if will be needed

# TODO OBGM: Not sure about params below
#grails:
#    exceptionresolver:
#        params:
#            exclude: ['password', 'passwordConfirm']
#    # scaffolding templates configuration
#    scaffolding:
#        templates:
#            domainSuffix: 'Instance'
#    # Set to false to use the new Grails 1.2 JSONBuilder in the render method
#    json:
#        legacy:
#            builder: false
#    # enabled native2ascii conversion of i18n properties files
#    enable:
#        native2ascii: true
#    # whether to install the java.util.logging bridge for sl4j. Disable fo AppEngine!
#    logging:
#        jul:
#            usebridge: true
#    # packages to include in Spring bean scanning
#    spring:
#        bean:
#            packages: []
#    # request parameters to mask when logging exceptions
#    exceptionresolver:
#        params:
#            exclude: ['password']
#    validateable:
#        packages: [
#        'org.pih.warehouse.inventory',
#        'org.pih.warehouse.fulfillment',
#        'org.pih.warehouse.order',
#        'org.pih.warehouse.request',
#        'org.pih.warehouse.shipment',
#]
